//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VTS.rc
//
#define IDD_ABOUTBOX                    100
#define ID_LNCOLINDEX                   101
#define IDD_NAMES                       102
#define IDC_LINENUMBER                  103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_NEWNAME                      105
#define IDC_DEVIMPORT                   106
#define ID_APPLY                        107
#define IDC_RESET                       108
#define ID_DELETENAME                   109
#define IDC_DEVEXPORT                   110
#define ID_IMPORTNAMES                  111
#define ID_EXPORTNAMES                  112
#define IDB_SCRIPTMAKE_120              120
#define IDB_SCRIPTCHECK_121             121
#define IDB_NBLINK_122                  122
#define IDB_BMALOGO_123                 123
#define IDR_MAINFRAME                   128
#define IDR_VTSTYPE                     129
#define IDR_VDBTYPE                     130
#define IDR_SUMMARYTYPE                 132
#define IDR_DEVTREE                     133
#define IDC_CURSOR1                     135
#define IDC_CURSOR2                     136
#define IDB_PACKETTREE                  140
#define IDD_PORT                        141
#define IDB_PORTSTATUS                  142
#define IDD_SENDIP                      143
#define IDD_SENDRAW                     144
#define IDD_SENDNPCI                    145
#define IDD_SENDNULL                    146
#define IDD_SENDVENDORNPDU              147
#define IDD_SENDWHOISRTN                148
#define IDD_SENDENET                    149
#define IDD_SENDIAMRTN                  150
#define IDD_SENDBVLCRESULT              151
#define IDD_SENDWRITEBDT                152
#define IDD_SENDREADBDT                 153
#define IDD_SENDREADBDTACK              154
#define IDD_SENDREGISTERFD              155
#define IDD_SENDREADFDT                 156
#define IDD_SENDREADFDTACK              157
#define IDD_SENDDELETEFDTENTRY          158
#define IDD_SENDBVLCI                   159
#define IDD_SENDTEST                    160
#define IDD_SENDICOULDBERTN             161
#define IDD_SENDREJECTMTN               162
#define IDD_SENDROUTERBUSY              163
#define IDD_SENDROUTERAVAIL             164
#define IDD_SENDINITRT                  165
#define IDD_SENDINITRTACK               166
#define IDD_SENDESTABLISHCTN            167
#define IDD_SENDDISCONNECTCTN           168
#define IDD_SENDSIMPLEACK               169
#define IDD_SENDSEGMENTACK              170
#define IDD_SENDERROR                   171
#define IDD_SENDREJECT                  172
#define IDD_SENDABORT                   173
#define IDD_SENDCHANGELISTERROR         174
#define IDD_SENDIAM                     175
#define IDD_SENDWHOIS                   176
#define IDD_SENDCREATEOBJECTERROR       177
#define IDD_SENDWRITEPROPMULTERROR      178
#define IDD_SENDVTCLOSEERROR            179
#define IDD_SENDIHAVE                   180
#define IDD_SENDWHOHAS                  181
#define IDD_SENDTIMESYNC                182
#define IDD_SENDUNCONFTEXTMSG           183
#define IDD_SENDCONFTEXTMSG             184
#define IDD_SENDCONFREQUEST             185
#define IDD_SENDCOMPLEXACK              186
#define IDD_SENDDEVICECOMMCTRL          187
#define IDD_SENDREINITDEVICE            188
#define IDD_ANY                         189
#define IDD_SENDREADPROP                190
#define IDD_SENDREADPROPACK             191
#define IDD_SENDWRITEPROP               192
#define IDD_SENDWRITEPROPMULT           193
#define IDD_SENDREADPROPMULT            194
#define IDD_SENDREADPROPMULTACK         195
#define IDD_SENDREADFILE                196
#define IDD_SENDREADFILEACK             197
#define IDD_SENDWRITEFILE               198
#define IDD_SENDWRITEFILEACK            199
#define IDD_SENDVTOPEN                  200
#define IDD_SENDVTOPENACK               201
#define IDD_SENDVTCLOSE                 202
#define IDD_SENDVTDATA                  203
#define IDD_SENDVTDATAACK               204
#define IDD_SENDADDLISTELEMENT          205
#define IDD_SENDCREATEOBJECT            206
#define IDD_SENDCREATEOBJECTACK         207
#define IDD_SENDDELETEOBJECT            208
#define IDD_SENDREMOVELISTELEMENT       209
#define IDD_TIMESTAMP                   210
#define IDD_SENDACKALARM                211
#define IDD_SENDCONFCOVNOTIFICATION     212
#define IDD_SENDGETALARMSUMMARY         213
#define IDD_SENDGETALARMSUMMARYACK      214
#define IDD_SENDCONFEVENTNOTIFICATION   215
#define IDD_NOTIFY_BITSTRING            216
#define IDD_NOTIFY_STATE                217
#define IDD_NOTIFY_VALUE                218
#define IDD_NOTIFY_CMDFAILURE           219
#define IDD_NOTIFY_FLOATLIMIT           220
#define IDD_NOTIFY_OUTOFRANGE           221
#define IDD_NOTIFY_COMPLEX              222
#define IDD_SENDGETENROLLMENTSUMMARY    223
#define IDD_RECIPIENTPROCESS            224
#define IDD_SENDGETENROLLMENTSUMMARYACK 225
#define IDD_SENDSUBSCRIBECOV            226
#define IDD_SENDUNCONFEVENTNOTIFICATION 227
#define IDD_SENDUNCONFCOVNOTIFICATION   228
#define IDD_PORTPAGE_ENET               229
#define IDB_PARMSTATUS                  230
#define IDD_PORTPAGE_PTP                233
#define IDD_SCRIPTPARMUPDATE            234
#define IDB_CONTENTSTATUS               235
#define IDD_SELECT_SESSION              236
#define IDD_OBJID                       237
#define IDD_SCRIPTLOADRESULTS           238
#define IDD_DEVICES                     239
#define IDD_SENDREADRANGE               240
#define IDD_SENDUTCTIMESYNC             241
#define IDD_GOTOLINE                    242
#define IDD_STATISTICS                  243
#define IDD_STATISTICS_OPTIONS          244
#define IDD_SENDDEVICE                  245
#define IDD_DEVICESTREE                 246
#define IDD_READALLPROPSETTING          247
#define IDD_LOADEPICSCONSCHK            248
#define IDD_SCRIPTMAKE                  249
#define IDD_SCRIPTCHECK                 250
#define IDD_OBJPROPVALUE                252
#define IDD_DATERANGE                   255
#define IDD_ADDRESSBINDING              256
#define IDD_CALENDARENTTRY              257
#define IDD_TIMESTAMP_CHOICE            258
#define IDD_DEVTREENULL                 259
#define IDD_DEVTREEDEV                  260
#define IDD_DEVTREEOBJ                  261
#define IDD_DEVTREEPROP                 263
#define IDD_DEVTREEVALUE                264
#define IDD_BTYPEGENERIC                266
#define IDB_DEVTREE                     268
#define IDD_PORTPAGE_IP                 269
#define IDD_PORTPAGE_NULL               270
#define IDD_PORTPAGE_ARCNET             271
#define IDD_PORTPAGE_MSTP               272
#define IDD_PREFERENCES                 273
#define IDD_DATETIME                    274
#define IDD_VENDORPROPID                276
#define IDD_SCRIPTINCLUDE               277
#define IDD_FILTERS                     278
#define IDD_LISTOF                      279
#define IDD_LISTOF_DESTINATION          280
#define IDD_DESTINATION                 281
#define IDD_SENDMSTP                    282
#define IDD_MSTPIMP_NBLINK              283
#define IDD_EPICSVIEW                   285
#define IDB_EPICSTREE                   286
#define IDD_NOTIFY_BUFFERREADY          287
#define IDD_SENDGETEVENTINFO            288
#define IDD_SENDGETEVENTINFOACK         289
#define IDD_LISTOF_TIMESTAMP            291
#define IDD_LISTOF_UNSIGNED             292
#define IDD_ACTION                      293
#define IDD_ACTIONCOMMAND               294
#define IDD_ACTIONLIST                  295
#define IDD_BINARYPV                    296
#define IDD_CLIENTCOV                   297
#define IDD_DAYSOFWEEK                  298
#define IDD_DEVICESTATUS                300
#define IDD_ENGIEERINGUNITS             301
#define IDD_DEVICEOBJECTREFERENCE       302
#define IDD_DEVICEOBJECTPROPREFERENCE   303
#define IDD_RECIPIENT                   304
#define IDD_OBJECTPROPERTYREFERENCE     305
#define IDD_COVSUBSCRIPTION             306
#define IDD_EVENTSTATE                  307
#define IDD_EVENTTRANSITIONBITS         308
#define IDD_FILEACCESSMETHOD            309
#define IDD_LIFESAFETYMODE              310
#define IDD_LIFESAFETYOPERATION         311
#define IDD_LIFESAFETYSTATE             312
#define IDD_EVENTTYPE                   313
#define IDD_LIMITENABLE                 314
#define IDD_LOGSTATUS                   315
#define IDD_MAINTENANCE                 316
#define IDD_NOTIFYTYPE                  317
#define IDD_OBJECTTYPE                  318
#define IDD_POLARITY                    319
#define IDD_PROGRAMERROR                320
#define IDD_PROGRAMREQUEST              321
#define IDD_PROGRAMSTATE                322
#define IDD_PROPERTYIDENTIFIER          323
#define IDD_RELIABILITY                 324
#define IDD_SEGMENTATION                325
#define IDD_SILENCESTATE                326
#define IDD_VTCLASS                     327
#define IDD_WEEKNDAY                    328
#define IDD_VTSESSION                   329
#define IDD_TIMEVALUE                   330
#define IDD_SETPOINTREFERENCE           331
#define IDD_SESSIONKEY                  332
#define IDD_RESULTFLAGS                 333
#define IDD_PROPERTYREFERENCE           334
#define IDD_PROPERTYSTATES              335
#define IDD_OBJECTPROPERTYVALUE         336
#define IDD_PROPERTYVALUE               337
#define IDD_PRIORITYVALUE               338
#define IDD_STATUSFLAGS                 339
#define IDD_PRIORITYARRAY               340
#define IDD_LOGRECORD                   341
#define IDD_DAILYSCHEDULE               342
#define IDD_OBJECTTYPESSUPPORTED        343
#define IDD_SERVICESSUPPORTED           344
#define IDD_SPECIALEVENT                345
#define IDD_LISTOF_BITSTRING            346
#define IDD_LISTOF_LIFESAFETYSTATE      347
#define IDD_LISTOFPROPERTYSTATES        348
#define IDD_EVENT_VALUE                 349
#define IDD_EVENT_STATE                 350
#define IDD_EVENT_OUTOFRANGE            351
#define IDD_EVENT_FLOATLIMIT            352
#define IDD_EVENT_LIFESAFETY            353
#define IDD_EVENT_CMDFAILURE            354
#define IDD_EVENT_BUFFERREADY           355
#define IDD_EVENT_BITSTRING             356
#define IDD_EVENTPARAMETER              357
#define IDD_LISTOFREADACCESSRESULT      358
#define IDD_LISTOFREADACCESSSPECIFICATION 359
#define IDD_EPICSVIEW_PROP              360
#define IDR_EPICS_PROP                  361
#define IDD_BACKUP_RESTORE              362
#define IDR_GLOBALBAR                   364
#define IDD_COLOR                       365
#define IDB_COLOR                       366
#define IDR_SUMMARYWIN                  368
#define IDI_RECVPKT                     369
#define IDD_SEND_RECEIVE_PROGRESS       370
#define IDI_SENDPKT                     371
#define IDD_EDITRESENTPKT               372
#define IDD_SENDSUBSCRIBECOVPROPERTY    373
#define IDD_NOTIFY_CHG_LS               375
#define IDD_NOTIFY_EXTENDED             376
#define IDD_NOTIFY_UNS_RANGE            377
#define IDD_DEVTREEOPT                  378
#define IDD_INCONSISTENT_PARS           379
#define IDD_SELECT_TEMPLATE             380
#define IDR_SCRIPT_CONTEXT              381
#define IDD_SENDWHATISNET               382
#define IDD_SENDNETNUMBERIS             383
#define IDD_DISCOVER_EPICS              384
#define IDD_DEVTREEOBJCOPY              385
#define IDC_PORTLIST                    1000
#define IDC_NAMELIST                    1001
#define IDC_NEWPORT                     1002
#define IDC_NAME                        1003
#define IDC_REMOVEDNET                  1004
#define IDC_NULLADDR                    1005
#define IDC_PORTNAME                    1006
#define IDC_REMOVEPROP                  1007
#define IDC_LOCALBROADCAST              1008
#define IDC_LOCALSTATION                1009
#define IDC_REMOTEBROADCAST             1010
#define IDC_REMOTESTATION               1011
#define IDC_GLOBALBROADCAST             1012
#define IDC_NETWORK                     1013
#define IDC_ADDRESS                     1014
#define IDC_LOCALSESSIONID              1015
#define IDC_SESSIONKEY                  1016
#define IDC_ACCEPT                      1017
#define IDC_REJECT                      1018
#define IDC_ENABLEPORT                  1019
#define IDC_DADR                        1020
#define IDC_NETWORK2                    1021
#define IDC_SADR                        1022
#define IDC_MAXAPDUSIZE                 1023
#define IDC_DATA                        1024
#define IDC_ENUMERATED                  1025
#define IDC_NEXTINVOKEID                1026
#define IDC_UNSIGNED                    1027
#define IDC_APDUTIMEOUT                 1028
#define IDC_INTEGER                     1029
#define IDC_APDUSEGTIMEOUT              1030
#define IDC_REAL                        1031
#define IDC_APDURETRIES                 1032
#define IDC_VERSION                     1033
#define IDC_DOUBLE                      1034
#define IDC_DNET                        1035
#define IDC_CHARSTR                     1036
#define IDC_PRIORITY                    1037
#define IDC_VENDORID                    1038
#define IDC_OCTETSTR                    1039
#define IDC_PERFINDX                    1040
#define IDC_PORTID                      1041
#define IDC_VALUE                       1042
#define IDC_HOPCOUNT                    1043
#define IDC_BITSTR                      1044
#define IDC_PORTINFO                    1045
#define IDC_FEEDBACKVALUE               1046
#define IDC_SNET                        1047
#define IDC_OBJID                       1048
#define IDC_DATE                        1049
#define IDC_DESTPRESENT                 1050
#define IDC_TIME                        1051
#define IDC_SRCPRESENT                  1052
#define IDC_MSGTYPE                     1053
#define IDC_PROPID                      1054
#define IDC_EXPECTINGREPLY              1055
#define IDC_DNETLIST                    1056
#define IDC_ADDDNET                     1057
#define IDC_SEGRESPONSE                 1058
#define IDC_BDTLIST                     1059
#define IDC_PROPLIST                    1060
#define IDC_ADDBDT                      1061
#define IDC_ADDPROP                     1062
#define IDC_REMOVEBDT                   1063
#define IDC_TTL                         1064
#define IDC_ADDR                        1065
#define IDC_TREMAIN                     1066
#define IDC_NONE                        1067
#define IDC_DBTN                        1068
#define IDC_RESULT                      1069
#define IDC_UNICAST                     1070
#define IDC_BROADCAST                   1071
#define IDC_FORWARD                     1072
#define IDC_OADR                        1073
#define IDC_BDTENTRY                    1074
#define IDC_BOOLEANCHECK                1075
#define IDC_ENUMERATEDCOMBO             1076
#define IDC_BOOLEAN                     1077
#define IDC_ADDFDT                      1078
#define IDC_REMOVEFDT                   1079
#define IDC_FDTLIST                     1080
#define IDC_FDTENTRY                    1081
#define IDC_REASON                      1082
#define IDC_TERMTIME                    1083
#define IDC_INVOKEID                    1084
#define IDC_SERVICECOMBO                1085
#define IDC_NAK                         1086
#define IDC_ERRORCLASSCOMBO             1087
#define IDC_DTDATE                      1088
#define IDC_CLIENT                      1089
#define IDC_ERRORCODECOMBO              1090
#define IDC_DTTIME                      1091
#define IDC_SERVER                      1092
#define IDC_ELEMENT                     1093
#define IDC_SEQNUM                      1094
#define IDC_PROPERTYID                  1095
#define IDC_WINDOWSIZE                  1096
#define IDC_INDEX                       1097
#define IDC_REJECTCOMBO                 1098
#define IDC_MAXSEGS                     1099
#define IDC_ABORTCOMBO                  1100
#define IDC_DEVICEID                    1101
#define IDC_MAXAPDULENGTH               1102
#define IDC_SEGMENTATIONCOMBO           1103
#define IDC_HIGHLIMIT                   1104
#define IDC_LOWLIMIT                    1105
#define IDC_OBJECTID                    1106
#define IDC_MOREITEM                    1107
#define IDC_ADDID                       1108
#define IDC_REMOVEID                    1109
#define IDC_IDLIST                      1110
#define IDC_TIMEREMAINING               1111
#define IDC_ID                          1112
#define IDC_OBJECTNAME                  1113
#define IDC_AUTOSYNC                    1114
#define IDC_MSG                         1115
#define IDC_SOURCEDEVICE                1116
#define IDC_CHARCLASS                   1117
#define IDC_NUMCLASS                    1118
#define IDC_NORMAL                      1119
#define IDC_URGENT                      1120
#define IDC_SEGMENTED                   1121
#define IDC_MOREFOLLOWS                 1122
#define IDC_SEQNUMBER                   1123
#define IDC_SEGCOUNTMSG                 1124
#define IDC_SEGMENTSIZE                 1125
#define IDC_ENABLE                      1126
#define IDC_DISABLE                     1127
#define IDC_TIMEDURATION                1128
#define IDC_PASSWORD                    1129
#define IDC_DISABLE_INIT                1130
#define IDC_CONTEXT                     1131
#define IDC_ELEMLIST                    1132
#define IDC_VENDOR                      1133
#define IDC_ADDELEM                     1134
#define IDC_ENCODED                     1135
#define IDC_REMOVEELEM                  1136
#define IDC_TYPECOMBO                   1137
#define IDC_ANY                         1138
#define IDC_PROPCOMBO                   1139
#define IDC_ARRAYINDEX                  1140
#define IDC_VALUECOMBO                  1141
#define IDC_LS_MODE                     1142
#define IDC_PRIORITYX                   1143
#define IDC_ISSUECONFIRMED              1144
#define IDC_PRIO                        1145
#define IDC_PROPVALUE_PRIORITY          1146
#define IDC_LS_OPERATION                1147
#define IDC_OBJLIST                     1148
#define IDC_STARTRECORD                 1149
#define IDC_OBJECTTYPECOMBO             1150
#define IDC_LIFETIME                    1151
#define IDC_POSTDELAY                   1152
#define IDC_ADDOBJ                      1153
#define IDC_RECORDCOUNT                 1154
#define IDC_MACADDRESS                  1155
#define IDC_REMOVEOBJ                   1156
#define IDC_REMOTESESSIONID             1157
#define IDC_FILEID                      1158
#define IDC_OBJUP                       1159
#define IDC_STARTPOSITION               1160
#define IDC_OBJDOWN                     1161
#define IDC_OCTETCOUNT                  1162
#define IDC_PROPUP                      1163
#define IDC_ADDRECORD                   1164
#define IDC_PROPDOWN                    1165
#define IDC_REMOVERECORD                1166
#define IDC_RECORDLIST                  1167
#define IDC_RECORDDATA                  1168
#define IDC_EOF                         1169
#define IDC_PORTCOMBO                   1170
#define IDC_VTCLASSCOMBO                1171
#define IDC_FNGROUPCOMBO                1172
#define IDC_SESSIONID                   1173
#define IDC_DATAFLAG                    1174
#define IDC_ADDRTYPECOMBO               1175
#define IDC_ALLDATAFLAG                 1176
#define IDC_ACCEPTEDCOUNT               1177
#define IDC_ACKPROCESSID                1178
#define IDC_ACKSOURCE                   1179
#define IDC_NOTIFYCLASS                 1180
#define IDC_EVENTSTATECOMBO             1181
#define IDC_TIMESTAMP                   1182
#define IDC_TIMEOFACK                   1183
#define IDC_PROCESSID                   1184
#define IDC_TOOFFNORMAL                 1185
#define IDC_TOFAULT                     1186
#define IDC_NOTIFYTYPECOMBO             1187
#define IDC_EVENTTYPECOMBO              1188
#define IDC_TONORMAL                    1189
#define IDC_FROMSTATECOMBO              1190
#define IDC_ADDSUMELEM                  1191
#define IDC_TOSTATECOMBO                1192
#define IDC_REMOVESUMELEM               1193
#define IDC_EVENTVALUES                 1194
#define IDC_ALARMSUMLIST                1195
#define IDC_ACKREQUIRED                 1196
#define IDC_MESSAGETEXT                 1197
#define IDC_REFBITSTRING                1198
#define IDC_INALARM                     1199
#define IDC_FAULT                       1200
#define IDC_OVERRIDDEN                  1201
#define IDC_OUTOFSERVICE                1202
#define IDC_CHANGEDVALUE                1203
#define IDC_SETPOINTVALUE               1204
#define IDC_CHANGEDBITS                 1205
#define IDC_ERRORLIMIT                  1206
#define IDC_COMMANDVALUE                1207
#define IDC_REFVALUE                    1208
#define IDC_EXCEEDINGVALUE              1209
#define IDC_DEADBAND                    1210
#define IDC_EXCEEDINGLIMIT              1211
#define IDC_ACKFILTERCOMBO              1212
#define IDC_MINPRIORITY                 1213
#define IDC_MAXPRIORITY                 1214
#define IDC_NOTIFICATIONCLASS           1215
#define IDC_RECIPIENTPROCESS            1216
#define IDC_ENROLLMENTSUMLIST           1217
#define IDC_UDP_PORT                    1218
#define IDC_ADAPTERCOMBO                1219
#define IDC_PROMISCUOUS                 1220
#define IDC_PARMNAME                    1221
#define IDC_PARMDESC                    1222
#define IDC_PARMSCRIPTVALUE             1223
#define IDC_PARMVALUE                   1224
#define IDC_PARMERRMSG                  1225
#define IDC_DOCLIST                     1226
#define IDC_DEVICEIDBTN                 1227
#define IDC_RESERVED                    1228
#define IDC_INSTANCE                    1229
#define IDC_OBJTYPECOMBO                1230
#define IDC_VALUEIDBTN                  1231
#define IDC_OBJIDBTN                    1232
#define IDC_OBJECTIDBTN                 1233
#define IDC_SOURCEDEVICEBTN             1234
#define IDC_FILEIDBTN                   1235
#define IDC_SADRCOMBO                   1236
#define IDC_DADRCOMBO                   1237
#define IDC_OADRCOMBO                   1238
#define IDC_ADDRCOMBO                   1239
#define IDC_MAXAPDULEN                  1240
#define IDC_VENDORNAME                  1241
#define IDC_MAX_SEGMENTS_ACCEPTED       1242
#define IDC_PRODUCTNAME                 1243
#define IDC_DEVICECOMBO                 1244
#define IDC_PRODUCTMODELNUMBER          1245
#define IDC_ROUTER                      1246
#define IDC_PRODUCTDESCRIPTION          1247
#define IDC_SEGTYPE                     1248
#define IDC_SEGBOTH                     1249
#define IDC_SEGTRANSMIT                 1250
#define IDC_SEGRECEIVE                  1251
#define IDC_RAW                         1252
#define IDC_SEGNONE                     1253
#define IDC_BTR                         1254
#define IDC_DEVICELIST                  1255
#define IDC_BBMD                        1256
#define IDC_NEWDEVICE                   1257
#define IDC_BIP                         1258
#define IDC_IAM                         1259
#define IDC_FOREIGN                     1260
#define IDC_SEGSIZE                     1261
#define ID_BBMDPEERS                    1262
#define ID_BTRPEERS                     1263
#define IDC_OBJPROP                     1264
#define IDC_HOSTADDR                    1265
#define IDC_DELETEDEVICE                1266
#define IDC_STARTDATUM                  1267
#define IDC_COUNT                       1268
#define IDC_REFINDEX                    1269
#define IDC_RADIONONE                   1270
#define IDC_RADIOPOSITION               1271
#define IDC_RADIOTIME                   1272
#define IDC_RADIOSEQUENCE               1273
#define IDC_TIMESTART                   1274
#define IDC_BEGDATECAPTION              1275
#define IDC_AUTOSYNCTIME                1276
#define IDC_UTCDATE                     1277
#define IDC_UTCTIME                     1278
#define IDC_STATICUTCDATE               1279
#define IDC_STATICUTCTIME               1280
#define IDC_EDIT_LINEINDEX              1281
#define IDC_BDTPORT                     1282
#define IDC_TOTALSEND                   1283
#define IDC_IP                          1284
#define IDC_TOTALRECEIVE                1285
#define IDC_MASK                        1286
#define IDC_IPSEND                      1287
#define IDC_IPRECEIVE                   1288
#define IDC_ETHERNETSEND                1289
#define IDC_ETHERNETRECEIVE             1290
#define IDC_ARCNETSEND                  1291
#define IDC_ARCNETRECEIVE               1292
#define IDC_IP_SEND                     1293
#define IDC_IP_SEND_CHECK               1294
#define IDC_MSTPSEND                    1295
#define IDC_MSTPRECEIVE                 1296
#define IDC_SERVICE_TREE                1297
#define IDC_PACKET_TYPE                 1298
#define IDC_PTPSEND                     1299
#define IDC_PTPRECEIVE                  1300
#define IDC_IP_RECEIVE_CHECK            1301
#define IDC_PACKET_TYPE_TEXT            1302
#define IDC_ETHERNET_SEND_CHECK         1303
#define IDC_ETHERNET_RECEIVE_CHECK      1304
#define IDC_ARCNET_SEND_CHECK           1305
#define IDC_ARCNET_RECEIVE_CHECK        1306
#define IDC_MSTP_SEND_CHECK             1307
#define IDC_MSTP_RECEIVE_CHECK          1308
#define IDC_PTP_RECEIVE_CHECK           1309
#define IDC_PTP_SEND_CHECK              1310
#define IDC_OVERALL_SEND_CHECK          1311
#define IDC_OVERALL_RECEIVE_CHECK       1312
#define IDC_SEL_ALL                     1313
#define IDC_CLEAR_ALL                   1314
#define IDC_RANGE_2                     1315
#define IDC_RANGE_3                     1316
#define IDC_RANGE_4                     1317
#define IDC_RANGE_5                     1318
#define IDC_OPTIONS                     1319
#define IDC_ADDCOMP                     1320
#define IDC_BAUDRATE                    1321
#define IDC_REMOVECOMP                  1322
#define IDC_COMPLIST                    1323
#define IDC_RPALL_NETWORK               1324
#define IDC_EPICSCONSRESULT             1325
#define IDC_SCRIPTMAKETEXT1             1326
#define IDC_DATETIME_DATE               1327
#define IDC_DATETIME_TIME               1328
#define IDC_DATERANGE_STARTDATE         1329
#define IDC_DEVICETREE                  1330
#define IDC_DATERANGE_ENDDATE           1331
#define IDC_CALENDARENTRY_STARTDATE     1332
#define IDC_ADDRESSBINDING_NETWORKNUMBER 1333
#define IDC_ACTIONCOMBO                 1334
#define IDC_CALENDARENTRY_ENDDATE       1335
#define IDC_ADDRESSBINDING_OBJECTID     1336
#define IDC_CALENDARENTRY_WEEKNDAY      1337
#define IDC_ADDRESSBINDING_MACADDRESS   1338
#define IDC_ADDRESSBINDING_OIDBUTTON    1339
#define IDC_CALENDARENTRY_DATERADIO     1340
#define IDC_CALENDARENTRY_DATERANGERADIO 1341
#define IDC_DEVTREEHOLDER               1342
#define IDC_CALENDARENTRY_WEEKNDAYRADIO 1343
#define IDC_CALENDARENTRY_DATE          1344
#define IDC_PROPISARRAY                 1345
#define IDC_TIMESTAMP_TIMERADIO         1346
#define IDC_TYPESHEETHOLDER             1347
#define IDC_TIMESTAMP_UNSIGNEDRADIO     1348
#define IDC_TIMESTAMP_DATETIMERADIO     1349
#define IDC_BTYPEDESCRIPTOR             1350
#define IDC_TIMESTAMP_TIME              1351
#define IDC_VALUEBOOL                   1352
#define IDC_TIMESTAMP_UNSIGNED          1353
#define IDC_TIMESTAMP_DATETIME_DATE     1354
#define IDC_TIMESTAMP_DATETIME_TIME     1355
#define IDC_PORTPAGE_HOLDER             1356
#define IDC_NOETHERNET                  1357
#define IDC_PREF_PACKETCOUNT            1358
#define IDC_PREF_ASTIMEOUT              1359
#define IDC_PREF_RELATIVE               1360
#define IDC_PREF_ABSOLUTE               1361
#define IDC_PREF_DELETEVERIFY           1362
#define IDC_PREF_LOADEPICS              1363
#define IDC_VENDOR_PROPID               1364
#define IDC_INCLUDEPLACE                1365
#define IDC_INCLUDEERROR                1366
#define IDC_INCLUDEICON                 1367
#define IDC_DESTINATION_NETWORK         1368
#define IDC_MSTPMAC                     1369
#define IDC_EPICSV_FILENAME             1370
#define IDC_REALINCR                    1371
#define IDC_TIMEDELAY                   1372
#define IDC_DISCLAIMER                  1373
#define IDC_DEVICEOBJINST               1374
#define IDC_RESENDINTERVAL              1375
#define IDC_EVENTS                      1376
#define IDC_RPALL_DA                    1377
#define IDC_MSTPMAXMASTER               1378
#define IDC_PROCESS_IDENTIFIER          1379
#define ID_NEWFILTER                    1380
#define IDC_RPALL_DNET_DADR             1381
#define IDC_MSTPMAXINFO                 1382
#define ID_DELETEFILTER                 1383
#define ID_IMPORTFILTERS                1384
#define ID_EXPORTFILTERS                1385
#define IDC_FILTERLIST                  1386
#define IDC_FILTERUP                    1387
#define IDC_FILTERDOWN                  1388
#define IDC_DNETPRESENT                 1389
#define IDC_LIST_LISTOF                 1390
#define IDC_USE_RPM                     1391
#define IDC_LISTOF_ADD                  1392
#define IDC_LISTOF_DELETE               1393
#define IDC_LISTOF_MODIFY               1394
#define IDC_DESTINATION_SUNDAY          1395
#define IDC_DESTINATION_MONDAY          1396
#define IDC_DESTINATION_TUESDAY         1397
#define IDC_DESTINATION_WEDNESDAY       1398
#define IDC_DESTINATION_THURSDAY        1399
#define IDC_DESTINATION_FRIDAY          1400
#define IDC_DESTINATION_SATURDAY        1401
#define IDC_DESTINATION_OFFNORMAL       1402
#define IDC_DESTINATION_FAULT           1403
#define IDC_DESTINATION_NORMAL          1404
#define IDC_DESTINATION_CONFIRM         1405
#define IDC_DESTINATION_ADDRESS         1406
#define IDC_DESTINATION__MACADDRESS     1407
#define IDC_DESTINATION_DEVICE          1408
#define IDC_DESTINATION_DEVICEID        1409
#define IDC_DESTINATION_DEVICEIDBTN     1410
#define IDC_REINITSTATE                 1411
#define IDC_DESTINATION_FROMTIME        1412
#define IDC_DESTINATION_TOTIME          1413
#define IDC_NBLINKSOCKET                1414
#define ID_NBLINKPARMS                  1415
#define ID_MSTPCONFIGIMP                1416
#define IDC_NBLINKLOCALPORT             1417
#define IDC_MSTPFRTYPECOMBO             1418
#define IDC_MSTPBAUD                    1419
#define IDC_MSTPIMP                     1420
#define IDC_NBLINKADDR                  1421
#define IDC_NBLINKSUBNETMASK            1422
#define IDC_NBLINKRESETADDR             1423
#define IDC_NBLINKRESET                 1424
#define IDC_NBLINKSTARTUP               1425
#define IDC_NBLINKGATEWAY               1426
#define IDC_EPICSV_LOAD                 1427
#define IDC_EPICSV_RESET                1428
#define IDC_EPICSV_TREE                 1429
#define IDC_EPICSV_EDIT                 1430
#define IDC_EPICSV_GEN                  1431
#define IDC_EPICSV_GENALL               1432
#define IDC_PRENOTIF                    1433
#define IDC_CURNOTIF                    1434
#define IDC_HASOBJID                    1435
#define IDC_EVENTINFOLIST               1436
#define IDC_SETTIMESTAMP                1437
#define IDC_SETPRIORITIES               1438
#define IDC_OFFNORMAL                   1439
#define IDC_OFFNORMAL1                  1440
#define IDC_FAULT1                      1441
#define IDC_NORMAL1                     1442
#define IDC_TIMESTAMPLIST               1443
#define IDC_UNSIGNEDLIST                1444
#define IDC_TIMERADIO                   1445
#define IDC_UNSIGNEDRADIO               1446
#define IDC_DATETIMERADIO               1447
#define IDC_MOREEVENT                   1448
#define IDC_QUITONFAIL                  1449
#define IDC_WRITESUCCESS                1450
#define IDC_BINARYPVCOMBO               1451
#define IDC_REALVALUE                   1452
#define IDC_NULLVALUE                   1453
#define IDC_DOFWEEK_MONDAY              1454
#define IDC_TIMECHANGE                  1455
#define IDC_DOFWEEK_TUESDAY             1456
#define IDC_DOFWEEK_WEDNESDAY           1457
#define IDC_DOFWEEK_THURSDAY            1458
#define IDC_DOFWEEK_FRIDAY              1459
#define IDC_DOFWEEK_SATURDAY            1460
#define IDC_DOFWEEK_SUNDAY              1461
#define IDC_ENUMRATECOMBO               1462
#define IDC_RADIODEVICE                 1463
#define IDC_WEEKOFMONTH                 1464
#define IDC_RADIOADDRESS                1465
#define IDC_DAYOFWEEK                   1466
#define IDC_ISSUECFMNTF                 1467
#define IDC_TIMEREMAIN                  1468
#define IDC_INCREMENT                   1469
#define IDC_LOGDISABLED                 1470
#define IDC_BUFFERPURGED                1471
#define IDC_MONTH                       1472
#define IDC_FIRSTITEM                   1473
#define IDC_LASTITEM                    1474
#define IDC_CHOICE                      1475
#define IDC_ONVALUE                     1476
#define IDC_BOOLVALUE                   1477
#define IDC_UNSIGNEDVALUE               1478
#define IDC_RADIONULL                   1479
#define IDC_RADIOBINARY                 1480
#define IDC_RADIOINTEGER                1481
#define IDC_RADIOVALUE                  1482
#define IDC_RADIOREAL                   1483
#define IDC_BINARYPV                    1484
#define IDC_ANYVALUE                    1485
#define IDC_LOGDATUM                    1486
#define IDC_ERRORCLASS                  1487
#define IDC_ERRORCODE                   1488
#define IDC_ENUMVALUE                   1489
#define IDC_INTERGERVALUE               1490
#define IDC_BITSTRINGVALUE              1491
#define IDC_HASSTATUSFLAGS              1492
#define IDC_AICHECK                     1493
#define IDC_AOCHECK                     1494
#define IDC_EVCHECK                     1495
#define IDC_AVCHECK                     1496
#define IDC_DECHECK                     1497
#define IDC_AVGCHECK                    1498
#define IDC_BICHECK                     1499
#define IDC_COCHECK                     1500
#define IDC_BOCHECK                     1501
#define IDC_BVCHECK                     1502
#define IDC_CACHECK                     1503
#define IDC_SELECTALL                   1504
#define IDC_FICHECK                     1505
#define IDC_GRCHECK                     1506
#define IDC_SCCHECK                     1507
#define IDC_LOCHECK                     1508
#define IDC_PRCHECK                     1509
#define IDC_LSPCHECK                    1510
#define IDC_LSZCHECK                    1511
#define IDC_NTCHECK                     1512
#define IDC_MSICHECK                    1513
#define IDC_MSOCHECK                    1514
#define IDC_MSVCHECK                    1515
#define IDC_TRCHECK                     1516
#define IDC_DEVCOMCTRL                  1517
#define IDC_ACKALARM                    1518
#define IDC_CFMCOVN                     1519
#define IDC_CFMEVN                      1520
#define IDC_GETALARMSUM                 1521
#define IDC_GETENRSUM                   1522
#define IDC_WRITEPROPM                  1523
#define IDC_LFSFTYO                     1524
#define IDC_GETEVNINFO                  1525
#define IDC_SUBSCOV                     1526
#define IDC_SUBSCOBPROP                 1527
#define IDC_ADDLIST                     1528
#define IDC_RMLIST                      1529
#define IDC_CREATOBJ                    1530
#define IDC_DELOBJ                      1531
#define IDC_READPROP                    1532
#define IDC_READPROPC                   1533
#define IDC_READPROPM                   1534
#define IDC_VTCLOSE                     1535
#define IDC_VTOPEN                      1536
#define IDC_VTDATA                      1537
#define IDC_AWRITEFILE                  1538
#define IDC_AREADFILE                   1539
#define IDC_REQUESTKEY                  1540
#define IDC_AUTHEN                      1541
#define IDC_TIMESYN                     1542
#define IDC_UCFMTEXTMSG                 1543
#define IDC_UCFMPRVTR                   1544
#define IDC_UCFMEVEN                    1545
#define IDC_IHAVE                       1546
#define IDC_UCFMCOVN                    1547
#define IDC_UTCTIMESYN                  1548
#define IDC_WHOHAS                      1549
#define IDC_READRANGE                   1550
#define IDC_WRITEPROP                   1551
#define IDC_WHOIS                       1552
#define IDC_CFMPRVTRANS                 1553
#define IDC_CFMTEXTMSG                  1554
#define IDC_REINITDEV                   1555
#define IDC_LISTOFTIMEVALUES            1556
#define IDC_RADIOCALENTRY               1557
#define IDC_RADIOOBJID                  1558
#define IDC_BITSTRING                   1559
#define IDC_BITSTRINGLIST               1560
#define IDC_ENUMLIST                    1561
#define IDC_BITMASK                     1562
#define IDC_LISTOFBSTR                  1563
#define IDC_NTFTHRESH                   1564
#define IDC_LISTOFAV                    1565
#define IDC_PREVIOUSNOTFC               1566
#define IDC_LISTOFLSFAV                 1567
#define IDC_LISTOFPROPSTATES            1568
#define IDC_RADIOBITSTR                 1569
#define IDC_EPICSV_PROP_LIST            1570
#define IDC_EPICSV_DA                   1571
#define IDC_ALLBACKUPRESTORE            1572
#define IDC_BACKUP_RESTORE_OUTPUT       1573
#define IDC_DOW3                        1574
#define IDC_DOW2                        1575
#define IDC_FULLBACKUPRESTORE           1576
#define IDC_BACKUP_RESTORE_KILL         1577
#define IDC_DOW1                        1578
#define IDC_RESTOREONLY                 1579
#define IDC_DOW4                        1580
#define IDC_AUXILIARYBACKUPRESTORE      1581
#define IDC_BACKUPONLY                  1582
#define IDC_COLORCOMBO1                 1583
#define IDC_BACKUPFILENAME              1584
#define IDC_AUTOSCROLL                  1585
#define IDC_ALLTESTS                    1586
#define IDC_RECVPKT                     1587
#define IDC_SAVESENTPKT                 1588
#define IDC_BROWSE                      1589
#define IDC_DESCOMBO                    1590
#define IDC_COLORCOMBO2                 1591
#define IDC_COLORCOMBO3                 1592
#define IDC_COLORCOMBO4                 1593
#define IDC_COLORCOMBO6                 1594
#define IDC_SNETCHECK                   1595
#define IDC_COLORCOMBO5                 1596
#define IDC_DNETCHECK                   1597
#define IDC_DELAY                       1598
#define IDC_BACKUPTIMEOUT               1599
#define IDC_INTERFACE                   1600
#define IDC_EVENTTYPE                   1601
#define IDC_EXVALUE                     1602
#define IDC_RADIO1                      1603
#define IDC_EXLIMIT                     1604
#define IDC_RADIO2                      1605
#define IDC_LS_STATE                    1606
#define IDC_SASUM                       1607
#define IDC_SESUM                       1608
#define IDC_INVALIDTAG                  1609
#define IDC_SINFO                       1610
#define IDC_MISSINGREQPAR               1611
#define IDC_TOOMANYARGS                 1612
#define IDC_LIST1                       1613
#define IDC_STATIC1                     1614
#define IDC_NUMERIC_TYPE                1615
#define IDC_TEXT_EDITOR                 1616
#define IDC_FILENAME                    1617
#define IDC_CHECK1                      1618
#define IDC_STATIC2                     1619
#define IDC_STATIC3                     1620
#define IDC_STATIC4                     1621
#define IDC_STATIC5                     1622
#define IDC_CHECK2                      1623
#define IDC_CHECK3                      1624
#define IDC_MFCLINK1                    1625
#define ID_VIEW_FIRSTFRAME              32771
#define ID_VIEW_PREVFRAME               32772
#define ID_VIEW_NEXTFRAME               32773
#define ID_VIEW_LASTFRAME               32774
#define ID_EDIT_PORTS                   32782
#define ID_EDIT_NAMES                   32783
#define ID_EDIT_CAPTUREFILTER           32785
#define ID_EDIT_DISPLAYFILTER           32786
#define ID_EDIT_PREFERENCES             32787
#define ID_EDIT_DELETE                  32788
#define ID_SCRIPT_CHECK_SYNTAX          32789
#define ID_SCRIPT_RUN                   32790
#define ID_SCRIPT_HALT                  32791
#define ID_SCRIPT_STEP                  32792
#define ID_SCRIPT_RESET                 32793
#define ID_SCRIPT_KILL                  32794
#define ID_SCRIPT_STEPPASS              32795
#define ID_SCRIPT_STEPFAIL              32796
#define ID_SEND_NEWPACKET               32797
#define ID_SEND_SENDAGAIN               32798
#define ID_EPICS_LOAD                   32801
#define ID_EPICS_LOADAUTO               32802
#define ID_EDIT_DEVICES                 32803
#define IDC_EDIT_GOTOLINE               32804
#define ID_VIEW_HEX                     32807
#define ID_VIEW_DETAIL                  32808
#define ID_VIEW_STATISTICS              32809
#define ID_FILE_EXPORT                  32810
#define ID_SCRIPT_ENV                   32811
#define ID_EPICS_READALLPROPERTY        32812
#define ID_FILE_WKS_NEW                 32814
#define ID_FILE_WKS_OPEN                32815
#define ID_FILE_WKS_SWITCH              32816
#define ID_FILE_WKS_SAVEAS              32817
#define ID_COLLAPSE_ITEMS               32818
#define ID_EXPAND_ITEMS                 32819
#define ID_SORT_ITEMS                   32820
#define ID_COPY_OBJECT                  32821
#define ID_NEWDEVICE                    32822
#define ID_NEWPROPERTY                  32823
#define ID_NEWOBJECT                    32824
#define ID_NEWVALUE                     32825
#define ID_DELETE                       32826
#define ID_NEWCOMPONENT                 32827
#define ID_EDIT_REFRESH                 32828
#define ID_SCRIPT_RUN1                  32829
#define ID_SCRIPT_CHECK_SYNTAX1         32830
#define ID_VIEW_EPICS                   32831
#define ID_BACKUP_RESTORE               32832
#define ID_EPICS_PROP_RP                32833
#define ID_EPICS_PROP_WP                32834
#define ID_EPICS_PROP_RPM               32835
#define ID_EPICS_PROP_WPM               32836
#define ID_EPICS_PROP_GEN               32837
#define ID_EPICS_PROP_CLEAR             32838
#define ID_EPICS_PROP_REUSE             32839
#define ID_VIEW_COLOR                   32839
#define ID_SAVEPKT                      32840
#define ID_GLOBAL_SCRIPT_CHECKSYNTAX    32849
#define ID_GLOBAL_SCRIPT_RESET          32850
#define ID_GLOBAL_SCRIPT_RUN            32851
#define ID_GLOBAL_SCRIPT_HALT           32852
#define ID_GLOBAL_SCRIPT_STEP           32853
#define ID_GLOBAL_SCRIPT_STEPPASS       32854
#define ID_GLOBAL_SCRIPT_STEPFAIL       32855
#define ID_GLOBAL_SCRIPT_KILL           32856
#define ID_GLOBAL_NEW_LOGFILE           32857
#define ID_GLOBAL_DISABLE_PORT          32858
#define ID_VIEW_GLOBALBAR               32861
#define ID_VIEW_MAINTOOLBAR             32862
#define ID_VIEW_GLOBAL_TOOLBAR          32863
#define ID_TESTS_INCONSISTENTPARS       32866
#define ID_EDIT_DELETESEL               32870
#define ID_EDIT_SENDPACKET              32871
#define ID_COMBOBOX_SEPARATOR           32873
#define ID_EDIT_QUICKSAVE               32874
#define ID_EDIT_AUTOSCROLL              32875
#define ID_SET_TEMPLATE_FILE            32877
#define ID_EDIT_LOGFILE                 32878
#define ID_EDIT_AUTO_OBJECT             32879
#define ID_EDIT_AUTO_PROPERTY           32880
#define ID_TOOLS_GENERATE_EPICS         32881
#define ID_TOOLS_DISCOVER_DEVICES       32882
#define ID_SCRIPT_TEMPLATE_0            32883
#define ID_SCRIPT_TEMPLATE_10           32893
#define ID_SCRIPT_TEMPLATE_20           32903
#define ID_SCRIPT_TEMPLATE_30           32913
#define ID_SCRIPT_TEMPLATE_LAST         32923
#define ID_FILE_MRU_WKS1                32934
#define ID_FILE_MRU_WKS2                32935
#define ID_FILE_MRU_WKS3                32936
#define ID_FILE_MRU_WKS4                32937
#define ID_FILE_MRU_WKS5                32938
#define ID_FILE_MRU_WKS6                32939
#define ID_FILE_MRU_WKS7                32940
#define ID_FILE_MRU_WKS8                32941
#define ID_FILE_MRU_WKS9                32942
#define ID_FILE_MRU_WKS10               32943
#define ID_FILE_MRU_WKS11               32944
#define ID_FILE_MRU_WKS12               32945
#define ID_FILE_MRU_WKS13               32946
#define ID_FILE_MRU_WKS14               32947
#define ID_FILE_MRU_WKSLAST             32948
#define IDS_BTYPE0                      32950
#define IDS_BTYPE1                      32951
#define IDS_BTYPE2                      32952
#define IDS_BTYPE3                      32953
#define IDS_BTYPE4                      32954
#define IDS_BTYPE5                      32955
#define IDS_BTYPE6                      32956
#define IDS_BTYPE7                      32957
#define IDS_BTYPE8                      32958
#define IDS_BTYPE9                      32959
#define IDS_BTYPE10                     32960
#define IDS_BTYPE11                     32961
#define IDS_BTYPE12                     32962
#define IDS_BTYPE13                     32963
#define IDS_BTYPE14                     32964
#define IDS_SCREX_COMPREAL              33000
#define IDS_SCREX_COMPEPICSNULL         33001
#define IDS_SCREX_COMPREALDATALEN       33002
#define IDS_SCREX_COMPDATANULL          33003
#define IDS_SCREX_COMPINT               33004
#define IDS_SCREX_COMPUINT              33005
#define IDS_SCREX_COMPARRAY             33006
#define IDS_SCREX_COMPSHORTDATA         33007
#define IDS_SCREX_COMPSTREAMFAIL_NE     33008
#define IDS_SCREX_COMPSTREAM_E          33009
#define IDS_SCREX_COMPEQREQ             33010
#define IDS_SCREX_COMP_TYPES_DIFFER     33011
#define IDS_SCREX_COMPSTRING            33012
#define IDS_SCREX_COMPFAILTYPE          33013
#define IDS_SCREX_COMPARRAYSIZE         33014
#define IDS_SCREX_COMPARRAYINXBOUNDS    33015
#define IDS_SCREX_COMPUNSUPPORTED       33016
#define IDS_SCREX_COMPFAIL              33017
#define IDS_SCREX_COMPFAILBITSTRING     33018
#define IDS_SCREX_COMPFAILENUM          33019
#define IDS_SCREX_COMPFAILPROP          33020
#define IDS_SCREX_COMPFAILDEVID         33021
#define IDS_SCREX_COMPFAILOBJID         33022
#define IDS_SCREX_COMPFAILSTRING        33023
#define IDS_SCREX_COMPFAILOCTSTRING     33024
#define IDS_SCREX_COMPFAILDOUBLE        33025
#define IDS_SCREX_COMPFAILREAL          33026
#define IDS_SCREX_COMPFAILINT           33027
#define IDS_SCREX_COMPFAILUNSIGNED      33028
#define IDS_SCREX_COMPFAILBOOL          33029
#define IDS_SCREX_COMPFAILSTRENCODING   33030
#define IDS_SCREX_COMPFAILDATE          33031
#define IDS_SCREX_COMPFAILTIME          33032
#define IDS_SCREX_INDEXUNSEXP           33033
#define IDS_SCREX_INDEXBOUNDS           33034
#define IDS_SCREX_INDEXUNSVAR           33035
#define IDS_SCREX_ASGN_UNDEFVAR         33036
#define IDS_SCREX_BADDATADATE           33037
#define IDS_SCREX_BADDATATIME           33038
#define IDS_SCREX_COMPFAILANY           33039
#define IDS_ERR_FILEPKTOPEN             34000
#define IDS_DEVTREE_CAPTION             34001
#define IDS_ERR_FILENOTPKT              34002
#define IDS_ERR_FILEMOVEON              34003
#define IDS_ERR_FILEOPENRCT             34004
#define IDS_ERR_FILEPKTRELOAD           34005
#define IDS_NEWPACKETFILENAME           34006
#define IDS_ERR_MAXPACKETS              34007
#define IDS_ERR_NOREALDEVICENAME        34008
#define IDS_ERR_TASKERROR               34009
#define ID_APP_CHECK_FOR_UPDATES        34010
#define ID_SW_NO                        45841
#define ID_SW_TIMESTAMP                 45842
#define ID_SW_PORT                      45843
#define ID_SW_SOURCE                    45844
#define ID_SW_DES                       45845
#define ID_SW_SNET                      45846
#define ID_SW_SADDR                     45847
#define ID_SW_DNET                      45848
#define ID_SW_DADDR                     45849
#define ID_SW_SERVICE                   45850
#define ID_EDIT_RECEIVEPKT              45900
#define ID_EDIT_SAVESENTPKT             45901
#define ID_EDIT_COLUMNVALUE             45902
#define ID_EDIT_SENDALLPACKET           45903
#define ID_EDIT_EDITSENDALLPKT          45904
#define IDS_WKS_SWITCH                  57346
#define IDS_WKS_OVERWRITE               57347
#define IDS_WKS_OVERWRITESAVE           57348
#define IDS_DELETEAREYOUSURE            57349
#define IDS_REGISTRYKEY                 57350
#define IDS_NAME_ADDRERROR              57682
#define IDS_FILTER_ADDRERROR            57683

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        385
#define _APS_NEXT_COMMAND_VALUE         34011
#define _APS_NEXT_CONTROL_VALUE         1626
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
